import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import type { Metadata } from "next";
import "./globals.css";
import { Box, Theme } from "@radix-ui/themes";
import NavBar from "./NavBar";
import { Inter } from "next/font/google";
import AuthProvider from "./auth/Provider";
import QueryClientProvider from "./QueryClientProvider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <QueryClientProvider>
          <AuthProvider>
            <Theme accentColor="iris" panelBackground="solid">
              <NavBar />
              <main className="p-5">
                <Box className="lg:px-20">{children}</Box>
              </main>
            </Theme>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
